### ISSUE TITLE
VSCode Stack depth is too high

### ISSUE THREAD

**Issue by yeminxuan** [nabla/vite-plugin-eslint#16]
I introduced the **@nabla/vite-plugin-eslint** plugin
<img width="649" alt="截屏2022-12-01 18 31 29" src="https://user-images.githubusercontent.com/65452224/205030100-69d3ebd5-1204-4bab-8162-443b90b97369.png">
You can see that TS reports an error：**Stack depth is too high**
<img width="763" alt="截屏2022-12-01 18 33 41" src="https://user-images.githubusercontent.com/65452224/205030515-8f801aef-3cdb-43a8-8af0-cc40a77ed0dc.png">

**Comment by yeminxuan** [comment]
How can this problem be solved?

**Comment by yeminxuan** [comment]
I switched to the **vite-plugin-eslint** plugin, and this still happened

**Comment by ArnaudBarre** [comment]
I'm not sure that the problem is related to the plugin.
This TS problem often appears when you have two versions of the project (here Vite) installed.
If you have yarn v1, you can use https://github.com/scinos/yarn-deduplicate, for other package manager it's probably built-in.
If you want more help, please provide a small reproduction via something like Stackblitz: https://antfu.me/posts/why-reproductions-are-required

Hope it help and happy to investigate any issue with the plugin once it's more easy for me to look into it
